### ISSUE TITLE
Memory leak in ToTop component

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#108]
**Description**
There is a memory leak in `ToTop` component.

A scroll event listener is added when the component is mounted via `useEffect`.
This event listener triggers the function `checkScrollTop`. This event triggers the function even when the component `ToTop` is removed.

**Solution**
Remove the event listener when the component is unmounted.
Check [this](https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup) for triggering cleanup function with hooks.

**Comment by alizahir23** [comment]
can I take up this issue and solve it along with the profile page?

**Comment by irshadjsr21** [comment]
Go ahead.
