### ISSUE TITLE
`newUser` undefined error while login

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#113]
**Describe**
This is the error occuring while login/signup. 
Tested in firefox (Ubuntu)
![image](https://user-images.githubusercontent.com/40335357/84273380-3992af00-ab4c-11ea-9e8e-380aa4a59361.png)

**Comment by Dishebh** [comment]
@irshadjsr21 I would like to work on this. Shall we redirect to the home page `/` if `newUser.user` is not defined.

**Comment by irshadjsr21** [comment]
If it's undefined logout user and return to home page.
