### ISSUE TITLE
"an unexpected error occurred" on profile page.

### ISSUE THREAD

**Issue by takshch** [OpenSouceCode/Frontend#121]
I opened profile in Firefox and i  am getting error : "an unexpected error occurred".

Console: 
 TypeError: "f.followingLanguages is undefined"
    NextJS 15

Screenshort:
![error-openSouceCode_profile](https://user-images.githubusercontent.com/26649558/84704907-321e3c00-af78-11ea-9d3f-53b36f78f616.png)

**Comment by vipulsnp** [comment]
Will resolve this one.
