### ISSUE TITLE
Allow the user to add experience level

### ISSUE THREAD

**Issue by Ashmn07** [OpenSouceCode/Frontend#125]
**Is your feature request related to a problem? Please describe.**

When the user is given projects to choose after choosing orgs and language, they might not get the projects they want like beginners might get slightly complex projects which might discourage them from continuing.

**Describe the solution you'd like**

We can ask the user to add their experience level(Beginner, Experienced) so that the beginners get projects which are not very difficult to understand and have a lot of good first issue labels. While the experienced can get comparatively more complex projects.

**Describe alternatives you've considered**

**Additional context**

**Comment by pravleen17** [comment]
I want to take this issue
