### ISSUE TITLE
Insertion of Favicon

### ISSUE THREAD

**Issue by eshaan007** [OpenSouceCode/Frontend#129]
The Website when in the Tabs, Looks plain. 
The favicon logo of OSC should be inserted. I found the "logo" in 'public ->logo -> favicon_logo' .

**Comment by eshaan007** [comment]
So can I take up this issue @irshadjsr21 ?

**Comment by irshadjsr21** [comment]
Sure, go ahead. @eshaan007

**Comment by eshaan007** [comment]
I have solved the Issue.. I have sent in a PR. Please check it !
