### ISSUE TITLE
Skill list in create OSP page is displayed incorrectly

### ISSUE THREAD

**Issue by vipulsnp** [OpenSouceCode/Frontend#132]
**Bug**
Form spacing changes with the skill list.
**Expected Behavior**
Form spacing should not change with the skill list.

**Comment by irshadjsr21** [comment]
Please add screenshots to clearly display the bug.

**Comment by vipulsnp** [comment]
**Initial State**
![image](https://user-images.githubusercontent.com/41316371/85295965-51f4b900-b4be-11ea-89ef-45a47af5db65.png)
**After adding skills**
![image](https://user-images.githubusercontent.com/41316371/85296074-75b7ff00-b4be-11ea-9b59-1d51657421dc.png)

The spacing between the two columns should remain same.
