### ISSUE TITLE
Add firebase validation rules

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#134]
**Description**
Add firebase validation rules so the only valid content is stored in firebase.

**Comment by garimasingh128** [comment]
Can you please elaborate the issue?

**Comment by irshadjsr21** [comment]
Firebase provides us the feature of `rules`, which we can write to specify who is allowed to write & read which data from your firestore. These rules also provide us with the feature of specifying what type of data is required for being stored in the firestore. In this task, you have add rules to validate the data being stored on firestore for different collections.
