### ISSUE TITLE
User experience on Initial login/signup

### ISSUE THREAD

**Issue by vipulsnp** [OpenSouceCode/Frontend#140]
**Is your feature request related to a problem? Please describe.**
On `first time login/signup` after the user selects the organisations and languages , he must be redirected to a page where he can add `username` and then to the feed page.

**Comment by vipulsnp** [comment]
Taking up this issue.

**Comment by pravleen17** [comment]
By mistake I have unassigned it . Please can you again assign it .I am so sorry for it.
