### ISSUE TITLE
Loading screen while signup popup is scrollable.

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#146]
**Description**
When a user tries to login/signup and a popup is displayed, the home page displays a loading screen. This loading screen is scrollable and the user can view the contents below it.

**Solution**
While the loading screen is displayed, the user should not be able to scroll through the contents.

**Comment by vipulsnp** [comment]
Should the components be displayed or not?

Solution 1:
Display loading spinner  when the login/signup popup is open.
![image](https://user-images.githubusercontent.com/41316371/86094092-aa831200-bacd-11ea-86c8-79253bd86021.png)

**Comment by vipulsnp** [comment]
@irshadjsr21 Resolved!!
