### ISSUE TITLE
Implement new repo filtering design on feed page

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#157]
**Description**
Implement this new filtering design on the feed page.
![Feed Section – 4](https://user-images.githubusercontent.com/40335357/86800594-d2a3df80-c090-11ea-8b6b-e621aebc9ce2.jpg)

**Comment by vipulsnp** [comment]
What will be the mobile view of this?

**Comment by takshch** [comment]
I can work on this issue but mobile design is required.

**Comment by vipulsnp** [comment]
@takshch I am already working on this one.

**Comment by takshch** [comment]
Okay.

**Comment by irshadjsr21** [comment]
@vipulsnp Always comment on the issue before working on it to avoid confusion. Also, the mobile view is in progress, for now you just need to implement the desktop view.

@takshch You can look into other issues.

**Comment by vipulsnp** [comment]
@irshadjsr21 This issue is now resolved.
