### ISSUE TITLE
Add the discussion form feature.

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#166]
**Description**
This feature will be just like a forum, people can open new discussions (for a particular repo) and other people can see and add comment to those discussions.

**Comment by divanshurox** [comment]
Hi I am new in Open Source, I wanted to work on this.

**Comment by aryasoni98** [comment]
Yes, Sure

**Comment by vipulsnp** [comment]
@divanshurox Any updates on this?
