### ISSUE TITLE
''How To Work" link is not working

### ISSUE THREAD

**Issue by Jayasree77** [OpenSouceCode/Frontend#168]
**Describe the bug**
The "How to Work" link in the nav-bar of home page is not working

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to Homepage
2. Click on 'How To Work'
3. See error

**Comment by irshadjsr21** [comment]
We need to remove the `How to work` link on the navbar.

**Comment by vipulsnp** [comment]
Working on this one @irshadjsr21

**Comment by mahimagoyalx** [comment]
Hi, can I also work on this issue?
