### ISSUE TITLE
The buttons at the bottom of the homepage have no links to their desired pages.

### ISSUE THREAD

**Issue by garimasingh128** [OpenSouceCode/Frontend#183]
**Describe the bug**
When we scroll down to the bottom of the landing page, we see different buttons like open source, open collective, edit this page etc. However, there are no hrefs present for these buttons for their respective places they should lead us to.

![Screenshot (561)](https://user-images.githubusercontent.com/44302373/89731117-2fb0fd80-da62-11ea-97bc-be92cc90819d.png)

**Expected behaviour**

Simply add the hrefs to the buttons.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows
 - Browser [e.g. chrome, safari] : Opera

** If you can mention the proper links in the comments then I would be happy to solve this issue!

**Comment by vipulsnp** [comment]
@garimasingh128 
These are the links:
Github : https://github.com/OpenSouceCode
View Source Code: https://github.com/OpenSouceCode/Frontend
Open Collective : https://opencollective.com/opensourcecode
Edit this page : https://github.com/OpenSouceCode/Frontend/tree/master/src/components
Replace `forum` with discord.
Discord : https://discord.gg/urV8vGk

Remove `code of conduct`
