### ISSUE TITLE
Non-functionality of the discussion box!

### ISSUE THREAD

**Issue by garimasingh128** [OpenSouceCode/Frontend#184]
![Screenshot (563)](https://user-images.githubusercontent.com/44302373/89731229-f331d180-da62-11ea-81d7-22903d83a54b.png)
**Describe the bug**
The discussion box is not functional. 
- The comment writing section is too broad and the discussion box is quite thin and present at the side which looks quite bad. When I type a comment and try to press the send button it doesn't work. Neither the attach button works when I press it to attach a file or image.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows
 - Browser [e.g. chrome, safari] : Opera

** I would be obliged if you can assign me this frontend issue to making the discussion box functional and neat-looking according to the design!

**Comment by vipulsnp** [comment]
This issue has already been raised . Issue #166
