### ISSUE TITLE
Menu Items are not Clickable

### ISSUE THREAD

**Issue by vipulsnp** [OpenSouceCode/Frontend#186]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the site on mobile
2. Login and Go to profile
3. Try to click the menu items
4. Menu Items cannot be clicked

**Expected behaviour**

Menu Items should be clickable.

**Additional context**

This might be due to the google adsense component  taking up space and having z-Index more than the menu items.

**Comment by Dishebh** [comment]
@vipulsnp can you pls provide a screenshot/gif that displays the issue? I am (somehow) not able to reproduce it.

**Comment by vipulsnp** [comment]
@Dishebh try reproducing using above steps.

**Comment by vipulsnp** [comment]
![image](https://user-images.githubusercontent.com/41316371/89787662-7a527880-db3b-11ea-88e2-64234783e466.png)

**Comment by Dishebh** [comment]
@vipulsnp I am able to click on them, even on smaller resolutions.

**Comment by vipulsnp** [comment]
Added z-index to menu Items. Handled in PR #191
