### ISSUE TITLE
Implement New Design for Project Details Page 

### ISSUE THREAD

**Issue by vipulsnp** [OpenSouceCode/Frontend#187]
Desktop View
![image](https://user-images.githubusercontent.com/41316371/91006932-5a6d8b00-e5f8-11ea-8377-4fb3e5936480.png)
Mobile View
![image](https://user-images.githubusercontent.com/41316371/91006965-6bb69780-e5f8-11ea-8a99-2c264fcf78a5.png)
![image](https://user-images.githubusercontent.com/41316371/91006969-6f4a1e80-e5f8-11ea-9250-46e2414fbaee.png)

**Comment by utchak160** [comment]
I want to work on this issue.
