### ISSUE TITLE
Redesign Discussion forum 

### ISSUE THREAD

**Issue by vipulsnp** [OpenSouceCode/Frontend#188]
Desktop View
![image](https://user-images.githubusercontent.com/41316371/89786054-f7302300-db38-11ea-892d-5937d15891cc.png)
Mobile View
![image](https://user-images.githubusercontent.com/41316371/89786105-0a42f300-db39-11ea-8b66-5331eb0888ad.png)

**Comment by nihalbaig0** [comment]
I will work on it.
