### ISSUE TITLE
Change the Project Info Page

### ISSUE THREAD

**Issue by vipulsnp** [OpenSouceCode/Frontend#225]
Change the project info page which is opened when clicking any repository,
![image](https://user-images.githubusercontent.com/41316371/93236683-bdd47e00-f79c-11ea-9a88-49a0b246140d.png)
This is the new design. 

**Leave** the `filter` section. That doesnt need to be added.

**Comment by FaizanKhan7** [comment]
# #225 
### I'll be doing this task.
