### ISSUE TITLE
[FEATURE]: Hacktoberfest Topic

### ISSUE THREAD

**Issue by Shaddamah** [OpenSouceCode/Frontend#238]
**Is your feature request related to a problem? Please describe.**

Since this month is Hacktoberfest 2020 and so many people trying to contribute to many open source code, i guess you it will be good to help them find codes to contribute by adding **hacktoberfest** topic to the repository

**Describe the solution you'd like**

Add **hacktoberfest** topic. By adding **hacktoberfest** topic to the repository there will be more contributor to this and other repository

**Comment by vipulsnp** [comment]
Since this repository is not specifically for `hacktoberfest`. It might not be good to add `hacktoberfest` as a topic.

**Comment by Shaddamah** [comment]
Well, okay then, thank you.
