### ISSUE TITLE
Smoother design

### ISSUE THREAD

**Issue by baris5d** [OpenSouceCode/Frontend#240]
When I looked at the website It looks like there's a design system but some elements have different approaches. I just changed some of elements in a way look better as an example. If you don't mind I'd like to apply all elements same effects.

Organization Page elements are too close to each other. It makes it more clear to give a better gap. I changed shadows also.
![organizations](https://user-images.githubusercontent.com/3397358/95095219-743fd900-0733-11eb-81e9-0d2f12ba9909.png)

On the top of Feed page, everything looks great. It has a high contrast but the following elements' margins, paddings and shadows make it broke. Here is an example for listing. (I didn't touch the sidebar yet)
![feed](https://user-images.githubusercontent.com/3397358/95095225-75710600-0733-11eb-9593-a72a88eca926.png)

If you assign me I'd love to make it.

**Comment by vipulsnp** [comment]
@baris5d You can work on this One. Make sure all breakpoints are covered.

**Comment by baris5d** [comment]
Okay I'm starting immediately. I'll send a pr asap.
