### ISSUE TITLE
Add login/signup functionality

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#25]
Create the UI for login/signup and implement it using firebase.

**Comment by anushbhatia** [comment]
Can I work on it

**Comment by alizahir23** [comment]
next already provides automatic routing. So react-router is not required. 
https://nextjs.org/docs/routing/introduction

**Comment by anushbhatia** [comment]
okay

**Comment by alizahir23** [comment]
what exactly has to be done in this feature?

**Comment by jmdmacapagal** [comment]
do you have a UI for this?
