### ISSUE TITLE
Browser Recognizing the website with Indonesian language

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [OpenSouceCode/Frontend#253]
**Describe the bug**

Browser Recognizing the website with Indonesian language.
**To Reproduce**

Steps to reproduce the behaviour:
1. Go to the website and wait for page to load.

**Expected behaviour**

Page loads without google translate dialog box.
**Screenshots**

![Screenshot 2020-10-22 150730](https://user-images.githubusercontent.com/70568620/96862806-99e31700-1483-11eb-950c-fb28d90e6de5.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 ]
 - Browser [chrome]

**Comment by vipulsnp** [comment]
@Prathamesh-Shanbhag Are you willing to work on this issue?

**Comment by Bihan001** [comment]
I would like to work on this issue.

**Comment by vipulsnp** [comment]
@Bihan001 Ok sure.

**Comment by Bihan001** [comment]
Fixed the google translate problem.

**Comment by vipulsnp** [comment]
Will review your PR.

**Comment by Bihan001** [comment]
Okay
