### ISSUE TITLE
sign in with github button not working

### ISSUE THREAD

**Issue by DhrutikPatel** [OpenSouceCode/Frontend#259]
**Describe the bug**
when you go to home page there is a **sign in with github** button 
on clicking give 404 Page not found button

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on this link https://opensourcecode.netlify.app/
2. Click on "**sign in with github** button"

**Expected behaviour**
It should redirect to sign in page of github

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by vipulsnp** [comment]
This is not an issue with frontend.
