### ISSUE TITLE
Integration of Vercel,Prettier and Eslint

### ISSUE THREAD

**Issue by anushbhatia** [OpenSouceCode/Frontend#41]
we should integrate vercel, prettier and eslint for deployment as its one of the important feature used nowadays.

**Comment by snitin315** [comment]
Vercel and eslint are done, prettier is still to be integrated

**Comment by irshadjsr21** [comment]
Nice thought but it's already integrated.

**Comment by irshadjsr21** [comment]
Sorry I was assuming prettier is already there.
