### ISSUE TITLE
Fix issue templates

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#44]
The issue template added in PR #35 is not working.

**Note**: Try renaming the `ISSUE_TEMPLATES` directory to `ISSUE_TEMPLATE`

**Comment by snitin315** [comment]
This is my bad, thanks for pointing out. I will send a fix.

**Comment by snitin315** [comment]
works well now.

![Screenshot at 2020-05-20 07-54-12](https://user-images.githubusercontent.com/46647141/82397909-26ba1c80-9a6f-11ea-9059-acf997b68f5f.png)
