### ISSUE TITLE
Use a design stsyem

### ISSUE THREAD

**Issue by snitin315** [OpenSouceCode/Frontend#53]
The need for Design Systems goes hand in hand with the need for scale, efficiency, and consistency in Design. 
Design Systems provides a shared library of reusable components and guidelines. Building products becomes much faster.

We can use some famous prebuilt systems like -

## [Ant Design](https://ant.design/)

Or we can create one with -

## [Styled Components](https://styled-components.com/)

Need feedback and discussion for which to choose.

**Comment by vipulsnp** [comment]
@irshadjsr21 @snitin315 I don't think it will be feasible to use design system now.

**Comment by athiratj** [comment]
Hi, @vipulsnp  please assign me this issue.

**Comment by vipulsnp** [comment]
@athiratj This one is stale and is no longer required, since we are writing own scss for components.

**Comment by athiratj** [comment]
Okay, fine.
