### ISSUE TITLE
Unnecessary usage of `eslint-disable` in `modal.jsx`

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#57]
**Description**
- The eslint react props are disabled in `src/components/modal.jsx`. Use prop types in the component and remove all `eslint-disable` comments.
- Also `<img>` tag should not be made clickable, instead, it should be wrapped in a button.

**Comment by vipulsnp** [comment]
This is handled alongside Issue #49  in PR #56 @irshadjsr21
