### ISSUE TITLE
Unnecessary usage of `eslint-disable` in `organisation.jsx`

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#58]
**Description**
- The eslint react props are disabled in `src/components/organisation.jsx`. Use prop types in the component and remove all `eslint-disable` comments.
- Also `<img>` tag should not be made clickable, instead, it should be wrapped in a button.

**Comment by vipulsnp** [comment]
Will work on this.

**Comment by irshadjsr21** [comment]
@vipulsnp Sure, but can you first work on #48? It's a bit urgent we fix the responsiveness issues.
