### ISSUE TITLE
Add header & footer css classes to style.css file

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#6]
The PR #5 removed header & footer CSS. Add the CSS classes for header & footer to the global `style.css` file.

**Comment by alizahir23** [comment]
The designs for the footer and header are in. Create an issue for the header as well and will update the files.

**Comment by irshadjsr21** [comment]
Ok, add both the component css on this issue.

**Comment by alizahir23** [comment]
Ok, will work on this issue tonight.
