### ISSUE TITLE
Feed page is not responsive.

### ISSUE THREAD

**Issue by alizahir23** [OpenSouceCode/Frontend#65]
**Describe the bug**

The feed page's responsive media queries doesn't kick in when its required to.

**Screenshots**

<img width="852" alt="Screenshot 2020-05-25 at 6 41 17 AM" src="https://user-images.githubusercontent.com/58049391/82769642-129d6300-9e53-11ea-8ec7-83773d2c482f.png">

**Comment by vipulsnp** [comment]
Provide full details of the bug. 
Steps to reproduce , dimensions where this occurs, device, and other relevant information. @alizahir23
