### ISSUE TITLE
Default user in context should be null

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#84]
**Describe the bug**
The default user is set to `Guest` in `_app.jsx` file.
https://github.com/OpenSouceCode/Frontend/blob/0af390d0e49f046603246600ee5113090a853510/pages/_app.jsx#L10

**Expected behavior**
It should be set to `null` to denote that the user hasn't logged in.
Use state should be: `useState(null)`

**Comment by vipulsnp** [comment]
Working on it
