### ISSUE TITLE
Typo in Bug Issue template

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#85]
**Describe the bug**
The bug issue template has a typo `behaviour` on line `18` in file `.github/ISSUE_TEMPLATE/Bug_Report.md`.

It should be `behavior`.

**Comment by snitin315** [comment]
Actually both the spellings are correct just like `color` and `colour`

**Comment by irshadjsr21** [comment]
Oh, then it's up to our preference. Let's keep it as it is.
