### ISSUE TITLE
Integrate forms in setting page with firebase

### ISSUE THREAD

**Issue by irshadjsr21** [OpenSouceCode/Frontend#89]
**Description**
The settings page currently have non-working forms for changing user profile.
Make those forms working by integrating firebase and changing the data.

**Comment by vipulsnp** [comment]
@irshadjsr21 I think this should be done using backend and database .

**Comment by irshadjsr21** [comment]
We'll be using firebase as our backend. The data will be stored with the user modal in the firebase.

**Comment by vipulsnp** [comment]
@irshadjsr21 This issue has been resolved.
