### ISSUE TITLE
Fix the image on the landing page.

### ISSUE THREAD

**Issue by alizahir23** [OpenSouceCode/Frontend#97]
![image](https://user-images.githubusercontent.com/58049391/83840438-2fbc1680-a71c-11ea-9345-ed0efb7b8e79.png)
The image is too small and taking up too much space.

**Comment by takshch** [comment]
I will fix this issue. I am new. Please guide me.

**Comment by irshadjsr21** [comment]
@takshch Sure, go-ahead. You can look at the Readme file for details on how to contribute.

**Comment by vipulsnp** [comment]
@irshadjsr21  This issue is resolved.
